version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imagenet-inference-app
    ports:
      - "8501:8501"
    volumes:
      # Mount models directory for easy model updates
      - ./models:/app/models
      # Mount app code for development (comment out for production)
      - ./app.py:/app/app.py
      - ./utils:/app/utils
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      # Add GPU support if available
      # - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
